### PR TITLE
Update Makefile.patch for v0.9.2

### PR DESCRIPTION
**Pull request by jsarenik**

### CODE REVIEW

**Comment by jsarenik** [comment]
@lvaccaro What do you think about adding it to the main C-lightning tree? Was there any discussion about it already which I am not aware of?

**Comment by lvaccaro** [comment]
I personally have no started any discussion, yet. I think there are two main issues to think about:
- this plugin requires some libraries which are not lightning dependency as openssl and curl: -lcurl -lssl -lcrypto
- this plugin should be manually disabled if you use standard bcli, because lightning loads by default all the compiled plugin in the plugin folder.

Maybe @vincenzopalazzo has a lightning branch with this plugin

**Comment by jsarenik** [comment]
Ah, thanks for explanation. It is good to talk about it first anyway. Let us get back to this discussion later.

What about this PR? :-)

**Comment by lvaccaro** [comment]
ack 4081fac3b0a2c86f7a82f6f40c166684c1a86998

**Comment by vincenzopalazzo** [comment]
Ops I arrived late to the party, sorry about that.

I want to add some of my ideas

> What do you think about adding it to the main C-lightning tree?

I don't think that it is a good idea for lighting the official project because is possible to have the same behavior with a plugin without changing the lighting build system. However, this will can have a sense if the lightning will fork the project and make two different forks, eg: a base code for android (or something like that), and server-side.

> Maybe @vincenzopalazzo has a lightning branch with this plugin

Yes, I have it on my personal fork, but it is buried under a lot of commits, if @jsarenik is interested we can work to maintain a branch with esplora update with the last version of lightnind.

**Comment by jsarenik** [comment]
@vincenzopalazzo I keep one such at https://github.com/jsarenik/lightning/commits/jsn/esplora (rebased to current lightning master and force-pushed a couple of times already)

**Comment by jsarenik** [comment]
@vincenzopalazzo here, [this fake PR](https://github.com/jsarenik/lightning/pull/1) will track any history of this branch.

**Comment by vincenzopalazzo** [comment]
@jsarenik Thanks to making this PR, it makes the tests easier also for us :smile:

**Pull request merged**
